### ISSUE TITLE
llda.so image not found, unsure what to do to make the c library

### ISSUE THREAD

**Issue by andykat** [TaskeHAMANO/LLDA#5]
I just ran make in both the submodules, but I get an error saying llda.so is not found. Could you tell me the steps to create the c library? Thanks

**Comment by amberheijden** [comment]
Hi Andy, I have the same issue. Did you solve it? How?

**Comment by datduong** [comment]
I also have the same problem.

**Comment by datduong** [comment]
> Hi Andy, I have the same issue. Did you solve it? How?

Hi, this is how I got the c library to work. I go inside the folder LLDA/lib/, and then I git clone the Labeled-LDA and the OnlineLDA_ParticleFilter. Now, I can go inside each of those folder to run make -f Makefile.

**Comment by Venousek** [comment]
> 
> 
> > Hi Andy, I have the same issue. Did you solve it? How?
> 
> Hi, this is how I got the c library to work. I go inside the folder LLDA/lib/, and then I git clone the Labeled-LDA and the OnlineLDA_ParticleFilter. Now, I can go inside each of those folder to run make -f Makefile.

Hi @datduong ,

I also have the same problem and tried your solution, but after compilation, I am still missing the shared .so files (only .o files are there). It seems that it should be configurable via parameters inside Makefile, but I wasn't able to figure it out correctly. Can you help, please?

EDIT: I was using original Labeled-LDA instead of https://github.com/TaskeHAMANO/Labeled-LDA and https://github.com/TaskeHAMANO/OnlineLDA_ParticleFilter and had to modify Makefile in both of them - add param -fPIC

**Comment by datduong** [comment]
Hi Venousek, I was only able to get the model to train. I wasn't able to get it to make prediction for new samples because some of the missing .so files were affecting this inference step. I ended up using the [python version](https://github.com/fann1993814/llda/issues/2).
